### PR TITLE
Remove mp3 support

### PR DESCRIPTION
**Pull request by ajbozarth**
Removes the dependancy on ffmpeg which is under a GPL license

### CODE REVIEW

**Comment by ajbozarth** [comment]
note: I'll do a through testing of this tomorrow

**Review by bdwyer2 — APPROVED** [review]
I guess we forgot to document MP3 support so no need to update the documentation. LGTM pending Travis CI results.

**Comment by ajbozarth** [comment]
I noticed that too, I actually made these edits entirely on GitHub.com so I still need to test it once docker hub finishes building

**Comment by ajbozarth** [comment]
I did some basic testing that wav files work and mp3 files error, once @frreiss gives a LGTM I'll merge this

**Comment by ptitzler** [comment]
Is the licensing issue specific to the library?

**Comment by ajbozarth** [comment]
@ptitzler Due to mp3 being patented until mid 2017, all the open source mp3 conversion tools are under some form of GPL license. This could change in the future now that the patents expired, but for now there's no way to convert to mp3 without using proprietary or GPL licensed software.

**Pull request merged**
